Feature/migration
scm-spain/OpenAds-demo pull request #1
Opened 2018-05-15 16:28 UTC by alextremp

This PR includes:

* The OpenAds demo project as it was included in the OpenAds repository
* It's still using the 2.2.0 version of OpenAds until the 3 version is released to use the connector dependencies

![](https://media.giphy.com/media/13UMwmUZdfuCw8/giphy.gif)

2018-05-16 08:45 UTC, rafamarquezv approved these changes
![](https://media.giphy.com/media/4TMqcN59kg3Yc/giphy.gif)

2018-05-17 10:20 UTC, victuxbb requested changes

2018-05-17 10:20 UTC, victuxbb commented on package.json
> +  "version": "2.2.0",
version 1.0.0 ?

2018-05-17 11:39 UTC, alextremp commented on package.json
> +  "version": "2.2.0",
I live in the future

2018-05-17 11:50 UTC, alextremp commented on package.json
> +  "version": "2.2.0",
done @victuxbb :)

2018-05-17 11:51 UTC, victuxbb approved these changes

2018-05-17 11:55 UTC, merged